### ISSUE TITLE
Finish tasks related to milestone 3

### ISSUE THREAD

**Issue by Spriz** [drunkenflamingos/drunkenflamingo-backend#11]
- [ ] A description of the purpose of the application
- [ ] Request data from a Web Service
- [ ] Publish data from your application as a Web Service
- [ ] Handle the authentication of the user
- [ ] Display data on a web page from your Web Service
- [ ] Submit a link to your repository on Github in this assignment.

**Comment by Spriz** [comment]
splitted into other issues in https://github.com/drunkenflamingos/drunkenflamingo-backend/milestone/4 than one big issue
